---
# ====== Application: シークレットの操作 =====================
id: 113
identification: 
  name: シークレットの操作
  alias: OCI-SECRET-PLSQL-SDK
  version: リリース1.0

row-search: 
  tokenize: true

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 21.2 / 22.1 / 22.2

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEXアカウント # 13750831515613219

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: WKSP_APEXDEV

globalization: 
  primary-language: Japanese (ja)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: シークレットの操作

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Black Text and White Background

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # ホーム

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu # 13914546945613308
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: ナビゲーション・メニュー # 13751697801613220

navigation-bar: 
  implementation: List
  list: ナビゲーション・バー # 13951952319613337
  list-template: Navigation Bar # 13914108876613308
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: シークレットの操作

- # ====== Substitution: G_COMPARTMENT_OCID ====================
  id: 2
  identification: 
    name: G_COMPARTMENT_OCID

  value: 
    static-value: ChangeMe

- # ====== Substitution: G_MASTER_KEY_OCID =====================
  id: 3
  identification: 
    name: G_MASTER_KEY_OCID

  value: 
    static-value: ChageMe

- # ====== Substitution: G_VAULT_OCID ==========================
  id: 4
  identification: 
    name: G_VAULT_OCID

  value: 
    static-value: ChangeMe

- # ====== Substitution: G_REGION ==============================
  id: 5
  identification: 
    name: G_REGION

  value: 
    static-value: us-ashburn-1

- # ====== Substitution: G_CREDENTIAL ==========================
  id: 6
  identification: 
    name: G_CREDENTIAL

  value: 
    static-value: MY_OCI_CRED

