---
- # ====== Search Configuration: 本文検索 - Oracle Text ========
  id: 49090274574620907651
  identification: 
    name: 本文検索 - Oracle Text
    search-query-prefix: content-text

  source: 
    search-type: Oracle Text (Manual)
    type: Table / View
    table-owner: Parsing Schema
    table-name: CDS_DOCUMENTS
    oracle-text-index-column: CONTENT

  column-mapping: 
    primary-key-1-column-name: ID
    title-column-name: TITLE
    custom-column-name-1: URL

  icon-and-badge: 
    icon-source: Icon Class

  advanced: 
    static-id: content_text

- # ====== Search Configuration: コード検索 - Oracle Text ======
  id: 49091425614101505226
  identification: 
    name: コード検索 - Oracle Text
    search-query-prefix: code-text

  source: 
    search-type: Oracle Text (Manual)
    type: SQL Query
    sql-query: |
      select a.id, d.title, d.url, a.raw_url, a.raw_content
      from cds_documents d join cds_attachments a 
        on d.id = a.post_id
    oracle-text-index-column: RAW_CONTENT

  column-mapping: 
    primary-key-1-column-name: ID
    title-column-name: TITLE
    custom-column-name-1: URL
    custom-column-name-2: RAW_URL

  icon-and-badge: 
    icon-source: Icon Class

  advanced: 
    static-id: code_text

- # ====== Search Configuration: 本文検索 - 標準 ===============
  id: 49104454930601420616
  identification: 
    name: 本文検索 - 標準
    search-query-prefix: content

  source: 
    search-type: Simple (APEX Data Source)
    location: Local Database
    type: Table / View
    table-owner: Parsing Schema
    table-name: CDS_DOCUMENTS
    searchable-columns: CONTENT

  column-mapping: 
    primary-key-1-column-name: ID
    title-column-name: TITLE
    custom-column-name-1: URL

  icon-and-badge: 
    icon-source: Icon Class

  advanced: 
    static-id: content

- # ====== Search Configuration: コード検索 - 標準 =============
  id: 49106264892954979767
  identification: 
    name: コード検索 - 標準
    search-query-prefix: code

  source: 
    search-type: Simple (APEX Data Source)
    location: Local Database
    type: SQL Query
    sql-query: |
      select a.id, d.title, d.url, a.raw_url, a.raw_content
      from cds_documents d join cds_attachments a 
        on d.id = a.post_id
    searchable-columns: RAW_CONTENT

  column-mapping: 
    primary-key-1-column-name: ID
    title-column-name: TITLE
    custom-column-name-1: URL
    custom-column-name-2: RAW_URL

  icon-and-badge: 
    icon-source: Icon Class

  advanced: 
    static-id: code

