
-- Generated by ORDS REST Data Services 21.4.2.r0621806
-- Schema: APEXDEV  Date: 火 4月  26 11:26:41 2022 
--

BEGIN
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'com.oracle.contacttracing',
      p_base_path      => '/contacts/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.contacttracing',
      p_pattern        => 'trace',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.contacttracing',
      p_pattern        => 'trace',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'declare
    l_user_id number;
    l_start_time date;
    l_end_time   date;
    l_distance number;
    l_time_tolerance_in_sec number;
    l_chaining_tolerance_in_sec number;
begin
    /* NVLで値がないときに結果が返るようにすることで、APEXのRESTの自動検出が使える */
    l_user_id := nvl(:user_id,7);
    l_start_time := nvl(:start_time,to_date(''2020-05-31 00:00:00'',''YYYY-MM-DD HH24:MI:SS''));
    l_end_time := nvl(:end_time,to_date(''2020-05-31 23:59:59'',''YYYY-MM-DD HH24:MI:SS''));
    l_distance := nvl(:distance,15);
    l_time_tolerance_in_sec := nvl(:time_tolerance_in_sec,5);
    l_chaining_tolerance_in_sec := nvl(:chaining_tolerance_in_sec,20);
    /* JSONオブジェクトの配列で結果を返す。 */
    apex_json.open_object;
    apex_json.open_array(''items'');
    for c in (
        SELECT
            ROWNUM AS contact_id,
            t.in_user_id,
            t.out_user_id,
            ROUND(t.duration / 60, 2) AS duration_in_minutes,
            t.start_time,
            t.end_time,
            t.num_contact_times' || ',
            t.geom
        FROM
            TABLE(
                sdo_obj_tracing.get_all_durations(
                    user_id                    => l_user_id,
                    start_time                 => l_start_time,
                    end_time                   => l_end_time,
                    distance                   => l_distance,
                    time_tolerance_in_sec      => l_time_tolerance_in_sec,
                    chaining_tolerance_in_sec  => l_chaining_tolerance_in_sec,
                    track_table_name           => ''track_geom'',
                    geom_column_name           => ''geom'',
                    user_id_column_name        => ''user_id'',
                    time_column_name           => ''capture_time'',
                    date_as_number_column_name => ''capture_time_as_number''
                )
            ) t
        WHERE
            t.segment_or_all = ''ALL''
        ORDER BY
            t.in_user_id,
            t.out_u' || 'ser_id,
            t.start_time
    )
    loop
        for p in (
            select p.x, p.y 
            from table(sdo_util.getvertices(c.geom)) p
        )
        loop
            apex_json.open_object;
            apex_json.write(''contact_id'', c.contact_id);
            apex_json.write(''in_user_id'', c.in_user_id);
            apex_json.write(''out_user_id'', c.out_user_id);
            apex_json.write(''duration_in_minutes'', c.duration_in_minutes);
            apex_json.write(''start_time'', c.start_time);
            apex_json.write(''end_time'', c.end_time);
            apex_json.write(''num_contact_times'', c.num_contact_times);
            apex_json.write(''x'', p.x);
            apex_json.write(''y'', p.y);
            apex_json.close_object;
        end loop;
    end loop;
    apex_json.close_array;
    apex_json.close_object;
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.contacttracing',
      p_pattern            => 'trace',
      p_method             => 'GET',
      p_name               => 'user_id',
      p_bind_variable_name => 'user_id',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.contacttracing',
      p_pattern            => 'trace',
      p_method             => 'GET',
      p_name               => 'start_time',
      p_bind_variable_name => 'start_time',
      p_source_type        => 'URI',
      p_param_type         => 'TIMESTAMP',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.contacttracing',
      p_pattern            => 'trace',
      p_method             => 'GET',
      p_name               => 'end_time',
      p_bind_variable_name => 'end_time',
      p_source_type        => 'URI',
      p_param_type         => 'TIMESTAMP',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.contacttracing',
      p_pattern            => 'trace',
      p_method             => 'GET',
      p_name               => 'distance',
      p_bind_variable_name => 'distance',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.contacttracing',
      p_pattern            => 'trace',
      p_method             => 'GET',
      p_name               => 'time_tolerance_in_sec',
      p_bind_variable_name => 'time_tolerance_in_sec',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.contacttracing',
      p_pattern            => 'trace',
      p_method             => 'GET',
      p_name               => 'chaining_tolerance_in_sec',
      p_bind_variable_name => 'chaining_tolerance_in_sec',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

        
COMMIT;

END;