
-- Generated by ORDS REST Data Services 23.1.4.r1501808
-- Schema: WKSP_APEXDEV  Date: 火 7月  04 06:53:32 2023 
--

DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'WKSP_APEXDEV',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'apexdev',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'rteditor',
      p_base_path      => '/rteditor/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rteditor',
      p_pattern        => 'image/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rteditor',
      p_pattern        => 'image/:id',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select content_type, image from rte_images where id = :id
');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rteditor',
      p_pattern        => 'image',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rteditor',
      p_pattern        => 'image',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'declare
    l_id rte_images.id%type;
begin
    /*
     * アップロードされた画像は:bodyにバイナリ・データとして保持されている。
     * :content_typeはORDSが設定してくれている。
     * :current_userはAPEXセッションによる保護をかけた場合、APP_USERになる。
     */
    insert into rte_images(content_type, image, created_by, created) 
        values(:content_type, :body, :current_user, sysdate)
        returning id into l_id;
    :status_code := 201;
    /*
     * アップロードに成功した場合は、urlとしてダウンロードするリンクをJSON形式で返す。
     * ex:
     * {
     *    "url": "https://hostname/ords/apexdev/rteditor/image/322343253253"
     *  }
     */
    apex_json.open_object;
    apex_json.write(
        p_name => ''url'',
        p_value => owa_util.get_cgi_env(''REQUEST_PROTOCOL'') ||
        ''://'' ||
        owa_util.get_cgi_env(''SERVER_NAME'') ||
        owa_util.get_cgi_env(''SCRIPT_NAME'') ||
        owa_util.get_cgi_env(''PATH_INFO'') ||
        ''/'' || l_id
    );
    apex_json.close_object;
exception
when others then
    /* エラーを返す。
     * {
     *   "er' || 'ror": {
     *       "message": "Something wrong!"
     *   }
     *  }
     */
    apex_json.open_object;
    apex_json.open_object(''error'');
    apex_json.write(''message'', ''Something wrong!'');
    apex_json.close_object;
    apex_json.close_object;
end;');

    
    
  l_roles(1) := 'RESTful Services';
  l_modules(1) := 'rteditor';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'rteditor',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => '画像付き文書',
      p_description    => NULL,
      p_comments       => NULL);

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;
        
COMMIT;

END;