
-- Generated by ORDS REST Data Services 21.3.2.r3271419
-- Schema: APEXDEV  Date: 月 2月  07 01:56:07 2022 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'APEXDEV',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'apexdev',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'oracle.error.4061',
      p_base_path      => '/ora4061/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.error.4061',
      p_pattern        => 'test004',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.error.4061',
      p_pattern        => 'test004',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'declare
    l_n number;
    l_stat varchar2(16);
begin
    -- 呼び出し前のパッケージのステータスを確認する。
    select status into l_stat from all_objects
    where object_type = ''PACKAGE BODY''
      and object_name = ''MY_PARENT_PKG''
      and owner = ''APEXDEV'';
    sys.htp.p(''SID='' || sys_context(''USERENV'',''SID'') || '',STATUS='' || l_stat);
    -- ファンクションの呼び出し。
    update pkg_test set n = my_parent_pkg.count_up(40);
    select n into l_n from pkg_test fetch first 1 rows only;
    sys.htp.p(to_char(l_n));
    -- 1０秒、処理を待つ。
    dbms_session.sleep(10);
    -- もう一度ファンクションの呼び出し。
    -- 引数が同じでもパッケージ変数が違うので値は変わる。
    begin
        update pkg_test set n = my_parent_pkg.count_up(40);
        select n into l_n from pkg_test fetch first 1 rows only;
    exception
        when others then
            null;
    end;
    sys.htp.p(to_char(l_n)); -- 例外が発生したときは値が変わらない。
    -- 呼び出し後のパッケージのステータスを確認する。
    select status into l_stat from all_objects
    where object_type = ''PACKAGE BODY''
      and object_name = ''MY_PARENT_PKG''
      and owner = ''APEXDEV'';
    sys.htp.p(''SID='' || sys_context(''USERENV'',''SID'') || '',STATUS='' || l_stat);
end;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.error.4061',
      p_pattern        => 'test005',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.error.4061',
      p_pattern        => 'test005',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'declare
    l_n number;
    l_stat varchar2(16);
    l_exp boolean := false;
begin
    -- 呼び出し前のパッケージのステータスを確認する。
    select status into l_stat from all_objects
    where object_type = ''PACKAGE BODY''
      and object_name = ''MY_PARENT_PKG''
      and owner = ''APEXDEV'';
    sys.htp.p(''SID='' || sys_context(''USERENV'',''SID'') || '',STATUS='' || l_stat);
    -- ファンクションの呼び出し。
    update pkg_test set n = my_parent_pkg.count_up(50);
    select n into l_n from pkg_test fetch first 1 rows only;
    sys.htp.p(to_char(l_n));
    -- 1０秒、処理を待つ。
    dbms_session.sleep(10);
    -- もう一度ファンクションの呼び出し。
    -- 引数が同じでもパッケージ変数が違うので値は変わる。
    begin
        update pkg_test set n = my_parent_pkg.count_up(50);
        select n into l_n from pkg_test fetch first 1 rows only;
    exception
        when others then
            l_exp := true;
            null;
    end;
    sys.htp.p(to_char(l_n)); -- 例外が発生したときは値が変わらない。
    -- もう一回トライする。
    if l_exp then
        begin
            update pkg_test set n = my_parent_pkg.count_up(50);
            select n into l_n from pkg_test fetch first 1 rows only;
        exception
            when others then
                null;
        end;
        sys.htp.p(to_char(l_n)); -- 例外が発生したときは値が変わらない。
    end if;
    -- 呼び出し後のパッケージのステータスを確認する。
    select status into l_stat from all_objects
    where object_type = ''PACKAGE BODY''
      and object_name = ''MY_PARENT_PKG''
      and owner = ''APEXDEV'';
    sys.htp.p(''SID='' || sys_context(''USERENV'',''SID'') || '',STATUS='' || l_stat);
end;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.error.4061',
      p_pattern        => 'test001',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.error.4061',
      p_pattern        => 'test001',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'declare
    l_n number;
    l_stat varchar2(16);
begin
    -- 呼び出し前のパッケージのステータスを確認する。
    select status into l_stat from all_objects
    where object_type = ''PACKAGE BODY''
      and object_name = ''MY_PARENT_PKG''
      and owner = ''APEXDEV'';
    sys.htp.p(''SID='' || sys_context(''USERENV'',''SID'') || '',STATUS='' || l_stat);
    -- ファンクションの呼び出し。
    l_n := my_parent_pkg.count_up(10);
    update pkg_test set n = l_n;
    sys.htp.p(to_char(l_n));
    -- もう一度ファンクションの呼び出し。
    -- 引数が同じでもパッケージ変数が違うので値は変わる。
    l_n := my_parent_pkg.count_up(10);
    update pkg_test set n = l_n;
    sys.htp.p(to_char(l_n));
    -- 呼び出し後のパッケージのステータスを確認する。
    select status into l_stat from all_objects
    where object_type = ''PACKAGE BODY''
      and object_name = ''MY_PARENT_PKG''
      and owner = ''APEXDEV'';
    sys.htp.p(''SID='' || sys_context(''USERENV'',''SID'') || '',STATUS='' || l_stat);
end;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.error.4061',
      p_pattern        => 'test000',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.error.4061',
      p_pattern        => 'test000',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'declare
    l_n number;
    l_stat varchar2(16);
begin
    -- 呼び出し前のパッケージのステータスを確認する。
    select status into l_stat from all_objects
    where object_type = ''PACKAGE BODY''
      and object_name = ''MY_PARENT_PKG''
      and owner = ''APEXDEV'';
    sys.htp.p(''SID='' || sys_context(''USERENV'',''SID'') || '',STATUS='' || l_stat);
    -- ファンクションの呼び出し。
    l_n := my_parent_pkg.count_up(0);
    update pkg_test set n = l_n;
    sys.htp.p(to_char(l_n));
    -- 呼び出し後のパッケージのステータスを確認する。
    select status into l_stat from all_objects
    where object_type = ''PACKAGE BODY''
      and object_name = ''MY_PARENT_PKG''
      and owner = ''APEXDEV'';
    sys.htp.p(''SID='' || sys_context(''USERENV'',''SID'') || '',STATUS='' || l_stat);
end;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.error.4061',
      p_pattern        => 'test002',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.error.4061',
      p_pattern        => 'test002',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'declare
    l_n number;
    l_stat varchar2(16);
begin
    -- 呼び出し前のパッケージのステータスを確認する。
    select status into l_stat from all_objects
    where object_type = ''PACKAGE BODY''
      and object_name = ''MY_PARENT_PKG''
      and owner = ''APEXDEV'';
    sys.htp.p(''SID='' || sys_context(''USERENV'',''SID'') || '',STATUS='' || l_stat);
    -- ファンクションの呼び出し。
    l_n := my_parent_pkg.count_up(20);
    update pkg_test set n = l_n;
    sys.htp.p(to_char(l_n));
    -- 1０秒、処理を待つ。
    dbms_session.sleep(10);
    -- もう一度ファンクションの呼び出し。
    -- 引数が同じでもパッケージ変数が違うので値は変わる。
    l_n := my_parent_pkg.count_up(20);
    update pkg_test set n = l_n;
    sys.htp.p(to_char(l_n));
    -- 呼び出し後のパッケージのステータスを確認する。
    select status into l_stat from all_objects
    where object_type = ''PACKAGE BODY''
      and object_name = ''MY_PARENT_PKG''
      and owner = ''APEXDEV'';
    sys.htp.p(''SID='' || sys_context(''USERENV'',''SID'') || '',STATUS='' || l_stat);
end;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.error.4061',
      p_pattern        => 'test003',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.error.4061',
      p_pattern        => 'test003',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'declare
    l_n number;
    l_stat varchar2(16);
begin
    -- 呼び出し前のパッケージのステータスを確認する。
    select status into l_stat from all_objects
    where object_type = ''PACKAGE BODY''
      and object_name = ''MY_PARENT_PKG''
      and owner = ''APEXDEV'';
    sys.htp.p(''SID='' || sys_context(''USERENV'',''SID'') || '',STATUS='' || l_stat);
    -- ファンクションの呼び出し。
    update pkg_test set n = my_parent_pkg.count_up(30);
    select n into l_n from pkg_test fetch first 1 rows only;
    sys.htp.p(to_char(l_n));
    -- 1０秒、処理を待つ。
    dbms_session.sleep(10);
    -- もう一度ファンクションの呼び出し。
    -- 引数が同じでもパッケージ変数が違うので値は変わる。
    update pkg_test set n = my_parent_pkg.count_up(30);
    select n into l_n from pkg_test fetch first 1 rows only;
    sys.htp.p(to_char(l_n));
    -- 呼び出し後のパッケージのステータスを確認する。
    select status into l_stat from all_objects
    where object_type = ''PACKAGE BODY''
      and object_name = ''MY_PARENT_PKG''
      and owner = ''APEXDEV'';
    sys.htp.p(''SID='' || sys_context(''USERENV'',''SID'') || '',STATUS='' || l_stat);
end;');

    
        
COMMIT;

END;