
-- Generated by ORDS REST Data Services 22.2.1.r2021302
-- Schema: WKSP_APEXDEV  Date: 火 8月  30 05:30:44 2022 
--

DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'WKSP_APEXDEV',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'apexdev',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'gridjs',
      p_base_path      => '/gridjs/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'gridjs',
      p_pattern        => 'emp/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'gridjs',
      p_pattern        => 'emp/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'declare
    l_json clob;
begin  
    select 
        json_object(
          ''data'' value coalesce(json_arrayagg(line),''[]'') format json
          , ''total'' value count(*)
        ) into l_json
    from (
        select json_object(empno, ename, job, sal, comm, hiredate) as line
        from emp
    );
    htp.p(l_json);
end;');

    
    
  l_roles(1) := 'RESTful Services';
  l_modules(1) := 'gridjs';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'gridjs',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'Grid.js',
      p_description    => NULL,
      p_comments       => NULL);

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;
        
COMMIT;

END;