
-- Generated by ORDS REST Data Services 19.4.6.r1421859
-- Schema: DBCLOUD_TEST  Date: 金 3月  26 09:08:17 2021 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'DBCLOUD_TEST',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'dbcloud_demo',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'test',
      p_base_path      => '/test/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'test',
      p_pattern        => 'cookie',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'test',
      p_pattern        => 'cookie',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin
   insert into xss_client_data(cookie) values(:body_text);
   commit;
end;');

    
        
COMMIT;

END;